#!/usr/bin/env python3
"""Generate TIMING.md from timings.jsonl.

Reads the per-phase timing records written by pipeline_runtime._write_timing_report
(one JSON object per generation) and renders a human-readable report with ASCII
bar charts and Mermaid diagrams showing where wall-clock time goes, cold vs warm.

Usage:
    python gen_timing_doc.py            # uses ./timings.jsonl -> ./TIMING.md
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "timings.jsonl"
OUT = ROOT / "TIMING.md"

# Friendly descriptions + coarse category for each phase label.
PHASE_INFO = {
    "prompt_encode":          ("Encode the text prompt (Gemma text-encoder, runs on CPU)", "Text encode"),
    "build_video_encoder":    ("Assemble the VAE video *encoder* (weights -> GPU)",         "Model assembly"),
    "encode_conditionings_s1":("VAE-encode the reference VIDEO + subject IMAGE (stage 1)",   "Conditioning encode"),
    "build_transformer_s1":   ("Assemble the 22B transformer for stage 1 (weights -> GPU, fp8 cast)", "Model assembly"),
    "denoise_stage1":         ("Stage-1 diffusion (low-res denoising loop)",                 "Diffusion"),
    "upsample_to_stage2":     ("Spatially upsample the stage-1 latent for stage 2",          "Upsample"),
    "build_transformer_s2":   ("Assemble the transformer for stage 2 (weights -> GPU)",      "Model assembly"),
    "encode_image_cond_s2":   ("VAE-encode the subject IMAGE again at full res (stage 2)",   "Conditioning encode"),
    "denoise_stage2":         ("Stage-2 diffusion (high-res refinement loop)",               "Diffusion"),
    "decode_video":           ("VAE-decode latents -> video frames (+build decoder cold)",   "VAE decode"),
    "decode_audio":           ("VAE-decode audio + vocoder (+build cold)",                   "VAE decode"),
    "mp4_encode":             ("Mux/encode the frames into the output .mp4",                 "Encode mp4"),
}


def load_last(kind: str) -> dict | None:
    rec = None
    for line in SRC.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        r = json.loads(line)
        if r.get("kind") == kind:
            rec = r
    return rec


def bar(pct: float, width: int = 40) -> str:
    n = int(round(pct / 100 * width))
    return "█" * n + "·" * (width - n)


def phase_table(rec: dict) -> str:
    total = rec["total_s"]
    rows = sorted(rec["phases"], key=lambda p: p["secs"], reverse=True)
    out = ["| Phase | Seconds | % of total | |",
           "|---|---:|---:|---|"]
    for p in rows:
        pct = 100 * p["secs"] / total if total else 0
        out.append(f"| `{p['name']}` | {p['secs']:.2f}s | {pct:.1f}% | `{bar(pct)}` |")
    out.append(f"| **TOTAL** | **{total:.1f}s** | **100%** | |")
    return "\n".join(out)


def category_rollup(rec: dict) -> list[tuple[str, float, float]]:
    total = rec["total_s"]
    cats: dict[str, float] = {}
    for p in rec["phases"]:
        cat = PHASE_INFO.get(p["name"], ("", "Other"))[1]
        cats[cat] = cats.get(cat, 0.0) + p["secs"]
    rows = sorted(cats.items(), key=lambda kv: kv[1], reverse=True)
    return [(c, s, 100 * s / total if total else 0) for c, s in rows]


def category_table(rec: dict) -> str:
    out = ["| Category | Seconds | % | |", "|---|---:|---:|---|"]
    for c, s, pct in category_rollup(rec):
        out.append(f"| {c} | {s:.2f}s | {pct:.1f}% | `{bar(pct)}` |")
    return "\n".join(out)


def mermaid_pie(rec: dict, title: str) -> str:
    out = [f"```mermaid", f"pie showData title {title}"]
    for c, s, _ in category_rollup(rec):
        out.append(f'    "{c}" : {s:.1f}')
    out.append("```")
    return "\n".join(out)


def phase_descriptions() -> str:
    out = ["| Phase | What it does | Category |", "|---|---|---|"]
    for name, (desc, cat) in PHASE_INFO.items():
        out.append(f"| `{name}` | {desc} | {cat} |")
    return "\n".join(out)


def main() -> None:
    cold = load_last("cold")
    warm = load_last("warm")
    if not cold and not warm:
        raise SystemExit(f"No records in {SRC}")

    ref = warm or cold
    md = []
    md.append("# Where the time goes — LTX-2 Motion-Transfer timing report\n")
    md.append("> Auto-generated by `gen_timing_doc.py` from real runs logged to "
              "`timings.jsonl`. Re-run it after any change to refresh the numbers.\n")
    md.append(f"**Measured config:** {ref['num_frames']} frames, {ref['height']}×{ref['width']}, "
              "fp8-cast, text-encoder on CPU, single GPU.\n")

    # TL;DR
    md.append("## TL;DR\n")
    if cold and warm:
        c_top = sorted(cold["phases"], key=lambda p: p["secs"], reverse=True)[:2]
        w_cat = category_rollup(warm)
        cond = next((p["secs"] for p in warm["phases"] if p["name"] == "encode_conditionings_s1"), 0.0)
        md.append(
            f"- **Cold start (first request) ≈ {cold['total_s']/60:.1f} min.** "
            f"It is almost entirely two one-time weight loads: "
            f"`{c_top[0]['name']}` ({c_top[0]['secs']:.0f}s) and "
            f"`{c_top[1]['name']}` ({c_top[1]['secs']:.0f}s). "
            "The GPU sits idle during this — it is disk/RAM-bound.\n"
            f"- **Warm request ≈ {warm['total_s']:.0f}s.** The biggest slices are "
            f"**{w_cat[0][0]}** ({w_cat[0][2]:.0f}%) and **{w_cat[1][0]}** ({w_cat[1][2]:.0f}%) — "
            "i.e. re-assembling models onto the GPU and encoding the prompt, **not** diffusion.\n"
            f"- **Caching the source-video vectors saves only ~{cond:.2f}s** "
            "(`encode_conditionings_s1`) on a warm request — it is *not* where the time goes. "
            "The real levers are keeping the assembled transformer resident on the GPU and "
            "caching the prompt embedding. See [Recommendations](#recommendations).\n")

    # Pipeline flow diagram
    md.append("## Pipeline flow (with warm-run times)\n")
    if warm:
        t = {p["name"]: p["secs"] for p in warm["phases"]}
        md.append("```mermaid")
        md.append("flowchart TD")
        md.append('    A["Prompt text"] -->|prompt_encode<br/>%.1fs| B["Stage 1 setup"]' % t.get("prompt_encode", 0))
        md.append('    B -->|build_video_encoder %.1fs| C["VAE encoder ready"]' % t.get("build_video_encoder", 0))
        md.append('    C -->|encode_conditionings_s1 %.2fs<br/>(video+image VAE)| D["Conditionings"]' % t.get("encode_conditionings_s1", 0))
        md.append('    D -->|build_transformer_s1 %.1fs| E["Transformer ready"]' % t.get("build_transformer_s1", 0))
        md.append('    E -->|denoise_stage1 %.1fs| F["Low-res latent"]' % t.get("denoise_stage1", 0))
        md.append('    F -->|upsample_to_stage2 %.1fs| G["Upscaled latent"]' % t.get("upsample_to_stage2", 0))
        md.append('    G -->|build_transformer_s2 %.1fs| H["Stage-2 transformer"]' % t.get("build_transformer_s2", 0))
        md.append('    H -->|denoise_stage2 %.1fs| I["Refined latent"]' % t.get("denoise_stage2", 0))
        md.append('    I -->|decode_video %.1fs + decode_audio %.1fs| J["Frames"]' % (t.get("decode_video", 0), t.get("decode_audio", 0)))
        md.append('    J -->|mp4_encode %.1fs| K["output .mp4"]' % t.get("mp4_encode", 0))
        md.append("```\n")

    # Cold
    if cold:
        md.append("## Cold start — first request after server start\n")
        md.append(f"Total: **{cold['total_s']:.0f}s (~{cold['total_s']/60:.1f} min)**\n")
        md.append("### By category\n")
        md.append(category_table(cold) + "\n")
        md.append(mermaid_pie(cold, "Cold start — time by category") + "\n")
        md.append("### By phase\n")
        md.append(phase_table(cold) + "\n")

    # Warm
    if warm:
        md.append("## Warm request — every request after the model is loaded\n")
        md.append(f"Total: **{warm['total_s']:.0f}s**\n")
        md.append("### By category\n")
        md.append(category_table(warm) + "\n")
        md.append(mermaid_pie(warm, "Warm request — time by category") + "\n")
        md.append("### By phase\n")
        md.append(phase_table(warm) + "\n")

    # Recommendations
    md.append("## Recommendations\n")
    md.append(
        "Ranked by payoff, based on the numbers above:\n\n"
        "1. **Eliminate the cold start for users — pre-warm at startup.** Start the server with "
        "`WARMUP_ON_STARTUP=1` so the ~20-min weight load happens before anyone connects. "
        "Already supported in `server.py`. This is the single biggest UX win.\n\n"
        "2. **Keep the assembled transformer resident on the GPU between requests.** "
        "On a warm request, `build_transformer_s1` (+`s2`) still costs ~12s because the model is "
        "re-assembled from the cached CPU state-dict and re-cast to fp8 on every call. Holding the "
        "built transformer on the GPU (instead of rebuilding) would remove most of this. Biggest "
        "*per-request* win.\n\n"
        "3. **Cache the prompt embedding for the fixed prompt.** `prompt_encode` costs ~10s warm "
        "(Gemma runs on CPU and is loaded/torn down each call). When the prompt is unchanged, cache "
        "the embedding and skip it. Second-biggest per-request win.\n\n"
        "4. **Do NOT bother caching the source-video latents for speed.** It targets "
        "`encode_conditionings_s1`, which is well under a second on a warm run. (It may still be worth "
        "it for *correctness/consistency*, but not for time.)\n")

    md.append("## How this was measured\n")
    md.append(
        "- `ltx_pipelines/utils/timing.py` — thread-local `tick()` profiler (syncs CUDA so GPU work "
        "is attributed to the right phase).\n"
        "- `ic_lora.py` `__call__` is annotated with one `T.tick(<phase>)` per stage boundary.\n"
        "- `pipeline_runtime.generate()` brackets the call with `T.begin()/report()`, times the mp4 "
        "mux, and appends a JSON record to `timings.jsonl` tagged `cold`/`warm`.\n"
        "- `cold` = weights not yet cached (first run / prewarm); `warm` = weights already in the "
        "shared `StateDictRegistry`.\n"
        "- Regenerate this file with `python gen_timing_doc.py`.\n")

    md.append("## Phase glossary\n")
    md.append(phase_descriptions() + "\n")

    OUT.write_text("\n".join(md), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
